FROM python:3.8-slim

ARG AY_AZURE_SQL_PASSWORD
ARG AY_AZURE_SQL_USERNAME
ENV AY_AZURE_SQL_PASSWORD=$AY_AZURE_SQL_PASSWORD
ENV AY_AZURE_SQL_USERNAME=$AY_AZURE_SQL_USERNAME

WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
CMD ["python", "app.py"]